name: Build and deploy Node.js app to Azure Web App - scrapFrontendproject

on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_PACKAGE_PATH: 'build'  # set this to the path to your web app project, defaults to the repository root
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
      - run: sudo rm -rf "/home/runner/work/KrowdyFrontProyect2/KrowdyFrontProyect2/node_modules"
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: add process.json
        run: |
          echo '{ script: "serve", env: { PM2_SERVE_SPA: "true", PM2_SERVE_HOMEPAGE: "/index.html" } }' >> build/process.json
    

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
      
        with:
          app-name: 'FrontVideoKrowdyProject'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A74DB37E63A341F5AD40DE379B2C20DF }}
          package: .